Neos:
  Flow:
    i18n:
      defaultLocale: de
  Neos:
    userInterface:
      defaultLanguage: de
      navigateComponent:
        nodeTree:
          loadingDepth: 1
      translation:
        autoInclude:
          'Dotpulse.Base': ['NodeTypes/*']
    fusion:
      autoInclude:
        'Dotpulse.Base': true
    nodeTypes:
      groups:
        product:
          position: 300
          label: 'Dotpulse.Base:NodeTypes.Groups:product'
        special:
          position: 400
          label: 'Dotpulse.Base:NodeTypes.Groups:special'
  Fusion:
    defaultContext:
      # usage: Dotpulse.Base.AssetTranslation.translate('de text | fr text | it text')
      # @see www/Neos/Packages/Plugins/Dotpulse.Base/Classes/Dotpulse/Base/Eel/Helper/AssetTranslationHelper.php
      'Dotpulse.Base.AssetTranslation': 'Dotpulse\Base\Eel\Helper\AssetTranslationHelper'

# Filenames are comma separated
#  * intern: Just the name e.g. "Main"
#  * extern: e.g. //ajax.googleapis.com/...
#  * If you want to add attributes, add it with square brackets e.g. Filename[data-prop data-attr="true"]

Dotpulse:
  Base:
    Context: 'Default'
    Source:
      GoogleTagManager:
      GoogleAnalytics:
      GoogleAnalyticsSendPageview: true
      GoogleSiteVerification:
      LazyLoading:
      Favicon:
      ThemeColor:
      SafariPinColor:
      MSapplicationTileColor:
      Name:
      GoogleFonts:
      VersionOfAssets: #add a value to prevent caching issues
      SupportIE8: false
      cleanHTML: true
      loadCSSAsynchron: false
      jQuery:
        old: '1.12.4'
        new: '3.0.0'
        printInHead: true
      General:
        CSS: #Filenames
        HeadJavascript: #Filenames
        BodyJavascript: #Filenames
        jQuery: #head OR body
      Backend:
        CSS: #Filenames
        HeadJavascript: #Filenames
        BodyJavascript: #Filenames
        jQuery: #head OR body
      Live:
        CSS: #Filenames
        HeadJavascript: #Filenames
        BodyJavascript: #Filenames
        jQuery: #head OR body
    Container:
      Filter: '[instanceof Neos.Neos:Document]'
      General: container
      AssetList: container
      Text: container
      TextWithImage: container
      Image: container
      Headline: container
    AssetList:
      titleTag: h3
    AssetTranslation:
      BySeparator: ~ # could be: '|'
    Image:
      maximumWidth: 2560
      openOriginalImageInLightbox: false
    TextWithImage:
      maximumWidth: 2560
      defaultAlignment: right
      style: Row # Row or Float
      rowClass: row
      firstlevel:
        left:
          text: 'text col-sm-8 col-sm-last'
          image: 'image col-sm-4 col-sm-first'
        right:
          text: 'text col-sm-8'
          image: 'image col-sm-4'
        top:
          text: text
          image: image
        bottom:
          text: text
          image: image
        float-left:
          text: text
          image: 'float-image-left image'
        float-right:
          text: text
          image: 'float-image-right image'
      nested:
        left:
          text: 'text col-md-8 col-md-last'
          image: 'image col-md-4 col-md-first'
        right:
          text: 'text col-md-8'
          image: 'image col-md-4'
        top:
          text: text
          image: image
        bottom:
          text: text
          image: image
        float-left:
          text: text
          image: 'float-image-left image'
        float-right:
          text: text
          image: 'float-image-right image'
