Neos:
  Flow:
    security:
      session:
        inactivityTimeout: 0

Dotpulse:
  Base:
    Source:
      GoogleTagManager: FALSE
      GoogleAnalytics: FALSE
      GoogleSiteVerification : FALSE
      Favicon: FALSE
